version: '3'

services:
    app:
        build: .
        container_name: app
        ports:
            - 8080:8080
        links:
            - mysql
        environment:
            SENDER_MAIL: enter email (gmail only) from which will be send emails
            MAIL_PASSWORD: enter pass for it email

    mysql:
        image: mysql/mysql-server:5.6
        container_name: mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=avitoParser
            - MYSQL_ROOT_HOST=%
        command: --init-file /data/application/init.sql
        volumes:
            - ./init.sql:/data/application/init.sql
